[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["cd backend && python -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python -m gunicorn app:app --bind 0.0.0.0:$PORT"
